domain: gabrielcano.com.br
url: https://gabrielcano.com.br

title: Gabriel Cano
email: gabriel@gabrielcano.com.br
author: Gabriel Cano

lang: pt-br

plugins:
  - jekyll-seo-tag

color: "#593b81"
secondary-color: "#00ff00"
# disqus:
#   shortname: example-com
#
rrss:
  email: "example@example.cl"
  telegram: "https://t.me/"
  discord: "https://discord.com/"

post:
  signature: Obrigado, Brasil. Bebam água, Bjos. ❤️